### ISSUE TITLE
bitmap working sample ?

### ISSUE THREAD

**Issue by dnovaes** [terratempest/android_niimprint#2]
HI, Thanks for sharing your work. I was glad to find it. Thanks to this repo i was able to send commands to my printer. But unfortunatelly wasn't able to print a valid bitmap yet. Could you share a working bitmap sample you have used on ur D11 printer ?

trying to figure out why my bitmap isn't being printed. Getting the error below:

<img width="1183" alt="Screenshot 2024-01-02 at 11 20 48 PM" src="https://github.com/terratempest/android_niimprint/assets/3251916/12a8781c-8d8f-46e0-8112-927a6180b8a3">

<img width="868" alt="Screenshot 2024-01-02 at 11 21 32 PM" src="https://github.com/terratempest/android_niimprint/assets/3251916/30d1b78b-ba23-47a3-a788-1d7fd73a868c">

hello image:
![hellosprite](https://github.com/terratempest/android_niimprint/assets/3251916/023cc219-4a41-4b5c-84c4-22f30bd361b8)

**Comment by dnovaes** [comment]
description edit with screenshots

**Comment by dnovaes** [comment]
Issue resolved. I'm able to print now but have to use the original width/height of the bitmap. Could not request smaller properties to print.

**Comment by basemomar94** [comment]
Hello @dnovaes 
Could you tell me what was the solution because I am facing the same issue?

**Comment by basemomar94** [comment]
Hello @dnovaes 
I can print but the image is very bad looking just some black ink 
although while printing with nibmot app it works fine
